### ISSUE TITLE
AttributeError: 'SingleTableMetadata' object has no attribute 'get'

### ISSUE THREAD

**Issue by running-machin** [sdv-dev/SDMetrics#363]
I have generated metadata as follows
```
from sdv.metadata import SingleTableMetadata
metadata = SingleTableMetadata()
metadata.detect_from_dataframe(data=df)
```

But when I use it 
```from sdmetrics.reports.single_table import QualityReport
my_report = QualityReport()
my_report.generate(df, synthetic_data, metadata)
```
I get the error
```
[/usr/local/lib/python3.10/dist-packages/sdmetrics/utils.py](https://localhost:8080/#) in get_columns_from_metadata(metadata)
    240             The columns metadata.
    241     """
--> 242     return metadata.get('columns', {})
    243 
    244 

AttributeError: 'SingleTableMetadata' object has no attribute 'get'
```
Moreover, U maynot  need this but I crate the synthetic data by
```import pandas as pd
from ctgan import CTGAN
ctgan = CTGAN(epochs=20)

df = pd.read_csv('Survey_US_Gleaned.csv',sep=';')
df = df.replace(',', '.', regex=True)
# change the data type to numeric
df = df.astype(float)

ctgan.fit(df,columns)

# Create synthetic data
synthetic_data = ctgan.sample(500)
```

I am using Google Collab to implement this. I hope somebody can help me with it

**Comment by npatki** [comment]
Hi @running-machin, nice to meet you.

The SDMetrics quality report expects your metadata to be a `dictionary` rather than a metadata object. You can use the `to_dict()` method to turn the object into a dictionary.

```python
metadata_dictionary = metadata.to_dict()

my_report = QualityReport()
my_report.generate(df, synthetic_data, metadata_dictionary)
```

### References 
For more information see:

- [Quality Report API docs](https://docs.sdv.dev/sdmetrics/reports/quality-report/single-table-api#generate-real_data-synthetic_data-metadata). This explains the types of inputs you need.
- [SDMetrics metadata description](https://docs.sdv.dev/sdmetrics/getting-started/metadata/single-table-metadata)
