### ISSUE TITLE
Too slow "Column Pair Trends"

### ISSUE THREAD

**Issue by echatzikyriakidis** [sdv-dev/SDMetrics#546]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDMetrics version: 0.13.1
* Python version: 3.10.12
* Operating System: Ubuntu 22.04.3 LTS (jammy)

### Error Description

Hi @npatki,

It seems that , it is too slow when running Column Pair Trends from Quality Report.

My current example:

Generating report ...
(1/4) Evaluating Column Shapes: : 100%|██████████| 59/59 [03:39<00:00,  3.72s/it]
(2/4) Evaluating Column Pair Trends: :   0%|          | 0/158 [00:00<?, ?it/s]

Suggestion:

Is it possible to change the library so that both single-table and multi-table reports (Quality+Diagnostic and any other that exists) to allow parallelization (either multithreading or multiprocessing) ?

Every calculation of column shapes or trends in column pairs can run in parallel. No need for sequential computation, since each computation is independent. Right?

Thanks!

**Comment by echatzikyriakidis** [comment]
OK, I have to say that after a change everything goes fast, but in reality I don't know exactly why because have no clue how the library works.

Many of my fields are high-cardinality ones with almost unique text values. So far, I had them as `pii=true` in the metadata and `sdtype=categorical`. I decided to remove sdtype completely but the library failed asking for sdtype field. Then I changed it to sdtype=test and now it runs very fast. Why is that? I don't care about these fields, I just want the library to skip them and not taking them account for column shapes or column pair trends.

Is there any other better approach of how to ignore them instead of setting them as pii? Should I remove them from the data before providing them to the library?

Thanks.

**Comment by npatki** [comment]
Hi @echatzikyriakidis, appreciate the feedback.

Before going to parallelization (which we certainly can look into), it is helpful to look back at metadata and ensure everything is running right. SDMetrics uses metadata to make sure it is applying the correct metrics. For example, if you are storing HTTP codes such as `404` (error not found), `500` (server error), `200` (ok), etc. then it should make sure to treat those as discrete categories instead of a numerical distribution.

[Here are the docs](https://docs.sdv.dev/sdmetrics/getting-started/metadata/single-table-metadata) for what the metadata should look like.

Based on your description, here's what I think is going on:

1. Sdtype `categorical` is not compatible with `pii`. If you mark something as categorical, SDMetrics will dutifully evaluate every single category, which could be a lot of categories if you really have some non-statistical, high cardinality value such as a text description. See [metadata spec](https://docs.sdv.dev/sdmetrics/getting-started/metadata/single-table-metadata#column-information). 
2. Any "other" sdtype (that is not categorical, numerical, datetime) is treated as a non-statistical value, meaning that it gets skipped. Therefore, when you apply `text`, it is skipping the column.

I would recommend continuing to use `text` to skip over columns that you do not want to include in the report. In the meantime, our team look into improving the experience for indicating which columns to skip.

**Comment by echatzikyriakidis** [comment]
Hi @npatki,

That's exactly what I ended up doing. I set those high cardinality text fields with sdtype=text and now everything is fast.

Thanks!

**Comment by npatki** [comment]
Thanks for confirming @echatzikyriakidis. I left a feature request in #548 so make it easier (and more intuitive) to specify which columns you want to ignore when generating a report.
