### ISSUE TITLE
Online documentation is not working at docs.sdv.dev/sdmetrics

### ISSUE THREAD

**Issue by echatzikyriakidis** [sdv-dev/SDMetrics#609]
Online documentation is not working at docs.sdv.dev/sdmetrics

**Comment by npatki** [comment]
Hi @echatzikyriakidis thanks for reporting. We're currently experiencing an docs outage but should be back up very shortly.

Do note that the actual SDMetrics package is still usable since it is a completely offline Python SDK. Until we get the docs back up, you can [view our tutorial notebook here](https://colab.research.google.com/drive/1fy3DNP_cH3a1QnQ1jyp3Sx49xborzg12?usp=sharing).

If you have any particular questions about SDMetrics, we are happy to support in the meantime. Otherwise, we are hoping the docs will be up soon.

**Comment by npatki** [comment]
@echatzikyriakidis -- and the site should be back up now https://docs.sdv.dev/sdmetrics

You may need to hard refresh. Do let us know if you're running into any more issues. Thanks.
