### ISSUE TITLE
Add optional metadata parameter to `get_pair_plot()`

### ISSUE THREAD

**Issue by srinify** [sdv-dev/SDMetrics#628]
### Problem Description

When visualizing pairs of columns using [get_pair_plot](https://docs.sdv.dev/sdmetrics/reports/visualization-utilities#compare-a-pair-of-synthetic-columns-and-real-columns-2d), it seems that the underlying dtypes in the DataFrame are being used to determine how to plot the data and how to format the resulting plot.

Similar to: https://github.com/sdv-dev/SDMetrics/issues/627

### Expected behavior

Gaurav had a good idea here -- let user optionally pass in their metadata dictionary when calling this function, which will act as the source of truth when generating the chart.

```python
from sdv.metadata.single_table import SingleTableMetadata
from sdmetrics.visualization import get_column_pair_plot

metadata = SingleTableMetadata()
metadata.detect_from_dataframe(real_table)

fig = get_column_pair_plot(
    real_data=real_table,
    synthetic_data=synthetic_table,
    column_names=['mba_perc', 'degree_perc'],
    metadata=metadata
    plot_type='scatter'
    
)

fig.show()
```

**Comment by npatki** [comment]
Chatted with @gsheni just now. 

The recommended approach is to use the `get_column_pair_plot` function through [the SDV library](https://docs.sdv.dev/sdv/single-table-data/evaluation/visualization#get_column_pair_plot) rather than import and use it from SDMetrics. The SDV's function is a wrapper around SDMetrics that includes the metadata already. SDV will look at the metadata and call SDMetrics with the appropriate plot type for the sdtype.

```python
from sdv.evaluation.single_table import get_column_pair_plot

fig = get_column_pair_plot(
    real_data=real_data,
    synthetic_data=synthetic_data,
    metadata=metadata,
    column_names=['mba_perc', 'degree_perc'],
    )
    
fig.show()
```

We have intentionally left SDMetrics as a general, open-source library that anyone can use independently of SDV and SDV-related concepts. So we would prefer not to use/import metadata within SDMetrics but rather use SDV wrappers.

Closing this issue off but feel free to reopen if I'm missing something.
